<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="2" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-12-13T08:11:11 IST" name="Default suite" finished-at="2024-12-13T08:12:35 IST" duration-ms="83763">
    <groups>
    </groups>
    <test started-at="2024-12-13T08:11:11 IST" name="Default test" finished-at="2024-12-13T08:12:35 IST" duration-ms="83763">
      <class name="com.seleniumdemo.listners.SwagLabsLoginTestWithData">
        <test-method signature="loginWithData(java.lang.String,java.lang.String)[pri:0, instance:com.seleniumdemo.listners.SwagLabsLoginTestWithData@18271936]" started-at="2024-12-13T08:12:00 IST" name="loginWithData" data-provider="excelDataRead" finished-at="2024-12-13T08:12:12 IST" duration-ms="12130" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[standard_user]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[secret_sauce]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginWithData -->
        <test-method signature="loginWithData(java.lang.String,java.lang.String)[pri:0, instance:com.seleniumdemo.listners.SwagLabsLoginTestWithData@18271936]" started-at="2024-12-13T08:12:12 IST" name="loginWithData" data-provider="excelDataRead" finished-at="2024-12-13T08:12:29 IST" duration-ms="16793" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[locked_out_user]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[secret_sauce]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at com.seleniumdemo.listners.SwagLabsLoginTestWithData.loginWithData(SwagLabsLoginTestWithData.java:47)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginWithData -->
        <test-method signature="loginWithData(java.lang.String,java.lang.String)[pri:0, instance:com.seleniumdemo.listners.SwagLabsLoginTestWithData@18271936]" started-at="2024-12-13T08:12:29 IST" name="loginWithData" data-provider="excelDataRead" finished-at="2024-12-13T08:12:34 IST" duration-ms="5949" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[problem_user]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[secret_sauce]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginWithData -->
      </class> <!-- com.seleniumdemo.listners.SwagLabsLoginTestWithData -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
